// Feeds the adapter's own projector output (generated by acp-agui-adapter's
// `golden_session_fixture` test) through the reducer. It fails when the adapter
// emits an event name or state key the reducer neither folds nor deliberately
// records, which is how a silent drop starts.
//
// Refresh the fixture: in acp-agui-adapter run
//   UPDATE_FIXTURES=1 cargo test golden_session_fixture
// then copy tests/fixtures/ag_ui_session.json to test/fixtures/adapter/.
import 'dart:convert';
import 'dart:io';

import 'package:ag_ui/ag_ui.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:ag_ui_widgets_flutter/src/model/conversation.dart';
import 'package:ag_ui_widgets_flutter/src/model/conversation_reducer.dart';

List<BaseEvent> _fixture() {
  final raw = jsonDecode(
          File('test/fixtures/adapter/ag_ui_session.json').readAsStringSync())
      as List;
  return [
    for (final e in raw)
      BaseEvent.fromJson(Map<String, dynamic>.from(e as Map)),
  ];
}

void main() {
  test('the reducer recognises everything the adapter emits', () {
    final r = ConversationReducer(namespace: 'episutra');
    for (final e in _fixture()) {
      r.apply(e);
    }
    // RAW events are deliberately recorded (not folded) and acp:source goes to
    // sourceRecords; anything else in the diagnostics is a drop.
    final unexpected = r.current.diagnostics
        .where((d) => d.kind != DiagnosticKind.raw)
        .toList();
    expect(unexpected, isEmpty,
        reason: 'unrecognised adapter output: '
            '${unexpected.map((d) => '${d.kind.name}:${d.name}').join(', ')}');
  });

  test('every adapter event name is one the reducer was written against', () {
    final names = {
      for (final e in _fixture())
        if (e is CustomEvent) e.name,
    };
    const known = {
      'acp:source',
      'acp.client_execute_request',
      'episutra:tool',
      'episutra:diff',
      'episutra:terminal',
      'episutra:content',
      'episutra:response_meta',
      'episutra:sync',
    };
    expect(names.difference(known), isEmpty,
        reason:
            'a new adapter CUSTOM event: handle it in the reducer, then add '
            'it to this list and to docs/event-vocabulary.md');
  });

  test('every state key the adapter emits is one the reducer reads', () {
    const known = {
      'agent',
      'mode',
      'commands',
      'config',
      'usage',
      'session_info',
      'plans',
      'permissions',
      'elicitations',
    };
    final keys = <String>{};
    for (final e in _fixture()) {
      if (e is StateSnapshotEvent) {
        final root = (e.snapshot as Map)['episutra'];
        if (root is Map) keys.addAll(root.keys.cast<String>());
      } else if (e is StateDeltaEvent) {
        for (final op in e.delta) {
          final v = op['value'];
          if (op['path'] == '/episutra' && v is Map) {
            keys.addAll(v.keys.cast<String>());
          }
        }
      }
    }
    expect(keys.difference(known), isEmpty,
        reason: 'the adapter writes a state key the reducer does not read '
            '(this is how the stray top-level currentModeId showed up)');
  });

  test('state and timeline from the fixture are fully populated', () {
    final r = ConversationReducer(namespace: 'episutra');
    for (final e in _fixture()) {
      r.apply(e);
    }
    final c = r.current;
    final s = c.sessionState;
    expect(s.agent!.agentInfo!.title, 'Claude');
    expect(s.mode!.currentModeId, 'code', reason: 'the CurrentModeChanged fix');
    expect(s.mode!.availableModes, hasLength(2));
    expect(s.commands!.commands.single.name, 'plan');
    expect(s.configState!.options.single.id, 'model');
    expect(s.usage!.used, 10);
    expect(s.sessionInfo!.title, 'Hello');
    expect(s.plans.byId.keys, containsAll(['p1', 'p2', 'p3']));
    expect(s.responseMeta, containsPair('session/new', {'a': 1}));
    expect(s.stopReason, 'end_turn');

    final tool = c.timeline
        .whereType<ToolCallTimelineItem>()
        .firstWhere((t) => t.id == 'tc1');
    expect(tool.locations.single.path, 'a.txt');
    expect(tool.diffs, hasLength(1));
    expect(tool.patches, hasLength(1));
    expect(tool.terminals.single.terminalId, 't1');
    expect(tool.media, hasLength(1));
    expect(tool.hasEnded, isTrue);
    expect(tool.resultParts, isNotEmpty);

    final permission =
        c.timeline.whereType<PermissionRequestTimelineItem>().single;
    expect(permission.content.single, isA<ToolContentTerminal>());
    final elicitation =
        c.timeline.whereType<ElicitationRequestTimelineItem>().single;
    expect(elicitation.scope!.kind, 'request');
    expect(c.timeline.whereType<MediaTimelineItem>(), hasLength(1));
    expect(c.timeline.whereType<ToolRequestTimelineItem>().single.toolName,
        'create_note');
    expect(c.sourceRecords, isNotEmpty);
  });
}
